[project]
name = "niricfg"
version = "0.0.2"
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet>=0.81.0",
    "kdl-py==1.2.0"
]

[dependency-groups]
dev = [
    "flet-cli>=0.81.0",
    "flet-desktop-light>=0.81.0",
    "flet-web>=0.81.0",
]
test = []

[tool.flet]
org = "codes.eeems"
product = "niricfg"
company = "Eeems"
copyright = "Copyright (C) 2026 by Eeems"

[tool.flet.app]
path = "src"

[tool.flet.compile]
app = true
packages = true

[tool.flet.cleanup]
app = true
packages = true

[tool.ruff]
exclude = [".venv", "build"]

[tool.ruff.lint]
extend-select = [
    "UP",
    "PL",
    "ANN",
    "S",
]
ignore = [
    "PLW0603",
    "PLR2004",
    "PLR0915",
    "PLR0912",
    "PLR0911",
    "PLR6301",
    "PLR0913",
    "S101",
    "S404",
    "S603",
    "S607",
    "ANN401",
    "ANN001",
    "ANN003",
    "BLE001"
]

[tool.pyright]
exclude = [".venv", "build"]
