name: Build application

on:
  workflow_dispatch:
  pull_request: &on-filter
    branches:
      - main
  push: *on-filter

permissions:
  packages: read

jobs:
  run:
    name: Build executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -e
          docker run \
            --volume=$(pwd):/src \
            --workdir=/src \
            ghcr.io/eeems/arkes-builder:niricfg \
            uvx flet build linux \
              --yes \
              --skip-flutter-doctor
          docker run \
            --volume=$(pwd):/src \
            --workdir=/src \
            ghcr.io/eeems/arkes-builder:niricfg \
            bash -c 'find build/linux/lib -type f | xargs strip'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/linux
          name: niricfg
